### ISSUE TITLE
mdk3 deauth

### ISSUE THREAD

**Issue by KaliMalibu** [FluxionNetwork/fluxion#425]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Fluxion is working fine, only mdk3 deauth have some problems.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I use Kali 2018.1 on MacBook (vm ware fusion) and Fluxion 4.4 (did try older versions to). I am able to get handshake with aireplay deauth if I use mdk3 deauth is not working. I only get message
"Periodically re-reading blacklist/ whitelist every 3 seconds. read failed: Network is down wi_read(): Network is down" sometimes it also close deauth window.
Major problem is I can not select aireplay deauth when I create evil twin AP. It automacly select mdk3 deauth, which do not want to work with fluxion in my case.

Can someone with more knowledge then me please help me.

Card I use is AWUS036NHA

mdk3 alone can be open in kali with no problem.

Thank you

#### What do you think the expected behaviour should be?
Do not know.
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by KaliMalibu** [comment]
Hi,

Here it is 

`#### FLUXION Info
FLUXION V4.4


#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy2
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)`

**Comment by MPX4132** [comment]
Yeah, you've got some other problem. Your wireless card is using the `ath9k_htc` which is known to work perfectly fine, so there's something else causing the issue. Make sure you have the very latest version of fluxion, since I fixed some bugs very recently.

**Comment by KaliMalibu** [comment]
Hi,

Thank you.  Can you please help me how to update to last version of Fluxion? Now I am running 4.4.

I am greenhorn in Linux

**Comment by MPX4132** [comment]
If you know how to use git, delete your current fluxion directory and reclone.

If you're not familiar, just go to the repository page (the main page) and click the green button, then click "Download Zip" extract it and try using that version.

**Comment by KaliMalibu** [comment]
I downloaded it once again (version 4.4) and I am still not able to use mdk3.
Is there any way to update mdk3 or something?

I was try to update it with command:

apt update && apt install pkg-config
apt-get install libnl-genl-3-200 libnl-genl-3-dev libnl-idiag-3-dev libpcap-dev
svn co https:/svn.mdk3.aircrack-ng.org/mdk3/
make install

but https:/svn.mdk3.aircrack-ng.org/mdk3/ is down.

**Comment by MPX4132** [comment]
The mdk3 included in Kali should work fine. To update everything, run:
```
apt update && apt upgrade -y && apt autoremove -y
```

**Comment by KaliMalibu** [comment]
Hi,

Just updated everything but I am still stuck. Is there any log file in fluxion or kali to see why mdk3 is not working? Is it possible problem is because I run kali in VM?

**Comment by MPX4132** [comment]
There's on log files for fluxion. You can try running it in debug mode, but I suggest you don't do that because your network interfaces will screw up.

Running it on a VM should be fine. I develop fluxion in a Kali VM.

**Comment by KaliMalibu** [comment]
Do I maybe need to set some permissions in Kali or fluxion? Can you help me with command in mdk3 how to manually set deauth, so I can test if mdk3 if working properly? I only open mdk3 and it opens OK, but I am not shure how tu set deauth? Can maybe something be wrong with card or drivers?

**Comment by spraragen88** [comment]
Hi, I have the same card and experienced the same issue, but I got mine to work. These are the steps I took, hopefully they will help you in some way.

apt update && apt install pkg-config (not sure if this helped, but its a step I took anyways)
apt-get install libnl-genl-3-200 libnl-genl-3-dev libnl-idiag-3-dev libpcap-dev (required to install MDK3)
svn co https://svn.mdk3.aircrack-ng.org/mdk3/

Then go into mdk3 folder, run make/make install

**Comment by KaliMalibu** [comment]
Hi,
Thank you for yours answer.
I found probably yours answer on other forum. Problem is that https://svn.mdk3.aircrack-ng.org/mdk3/ is down

**Comment by MPX4132** [comment]
@KaliMalibu To manually do deauthentication with mdk3, do the following:

Get the target network's MAC address, and channel. If you don't know how to do that, follow this:
```
airmon-ng start INTERFACE_HERE # put an interface in monitor mode

airodump-ng MONTOR_INTERFACE_HERE # the monitor interface that was created in the step above.
```
Look at the far right, find the network name and note the mac address and channel in the same line.
Close the window and now we can try deauthentication with mdk3.

```
echo "XX:XX:XX:XX:XX:XX" > jammed.lst # replace the XX:XX:XX:XX:XX:XX with the target MAC address.

mdk3 MONITOR_INTERFACE_HERE d -c CHANNEL_HERE -b jammed.lst
```

That should start deauthenticating the target network. Make sure you're doing this on a network you're allowed to test with. You're liable for anything you do. Don't do anything illegal.

**Comment by KaliMalibu** [comment]
Hi,

Thank you for yours help. I try to do attack with yours instruction and it fails at same point as in Fluxion
All I get is "periodically re-reading blacklist/whitelist every 3 seconds"

My guess is that something is wrong with mdk3 and not Fluxion?

Problem is that link for md3  https://svn.mdk3.aircrack-ng.org/mdk3/ is down for few days and I am not able to make update or reinstall of mdk3. Is there any mirror for  https://svn.mdk3.aircrack-ng.org/mdk3/ ?

And yes, I am doing this on my home network, thank you for yours warning :)

**Comment by spraragen88** [comment]
Oh, sorry. I didn't realize it was down. I think it's because they recently moved everything to github from their svn. 

Try getting mdk3 from here: https://github.com/aircrack-ng/mdk3

**Comment by MPX4132** [comment]
@KaliMalibu Let me clarify, if mdk3 is working correctly, **you should get this message:**
```
periodically re-reading blacklist/whitelist every 3 seconds.
```

**Comment by deltaxflux** [comment]
Additionally, mdk3 works only if airodump-ng is running.

**Comment by MPX4132** [comment]
My mdk3 works fine without airodump-ng, but the interface must be in monitor mode.

**Comment by deltaxflux** [comment]
Disagree with that try it.

**Comment by MPX4132** [comment]
There's no need for airodump-ng, it works standalone. Check out [this demo](https://github.com/FluxionNetwork/fluxion/files/1817007/mdk3_demo.zip) I just recorded.

The phone was connected to the network I used mdk3 with.

**Comment by deltaxflux** [comment]
Well, interesting that it works. For me it doesn't work as I said but I was curious to see that it worked for you.

**Comment by MPX4132** [comment]
That's pretty weird huh. It sucks that everyone's devices work differently. I wonder what's up with that. Are you using the same driver I'm using (ath9k_htc)?

**Comment by deltaxflux** [comment]
Yeah was pretty confusing. Well, I use the same driver. The only difference is that I use arch so maybe the packages are different.

**Comment by rad4day** [comment]
Just tested it with my AWUS036NHA on ArchLinux works flawlessly. @deltaxflux your Installation has some weird quirks as we already noticed ;)

```bash
$ sudo iw phy phy1 interface add mon0 type monitor
$ echo "50:2e:5c:XX:XX:XX" > blacklist
$ sudo mdk3 mon0 d -b blacklist
```

More INFO:
```
$ sudo mdk3 | head -n2 | tail -n1
MDK 3.0 v6 - "Yeah, well, whatever"
```
```
$ uname -a      
Linux ThinkPad 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
```

**Comment by MPX4132** [comment]
Yeah, I hate how inconsistent the behavior is across all the different devices and installations.

**Comment by rad4day** [comment]
@KaliMalibu Could you try another USB-Cable¹ and make sure that the NetworkManager is actually stopped?

[1] [https://forum.aircrack-ng.org/index.php?topic=976.0](https://forum.aircrack-ng.org/index.php?topic=976.0)

**Comment by deltaxflux** [comment]
Well these quirks have nothing to do with it. As you might noticed I fixed them.

**Comment by KaliMalibu** [comment]
Hi,

Thank you for all yours answers. I install mdk3 one more time from link that spraragen88 provide. Now mdk3 is working as standalone and also in Fluxion.

My discover is:

Befoure I did reinstall of mdk5 I only get message "periodically re-reading blacklist/whitelist every 3 seconds" but yes, MPX4132 was right, deauth was working. My phone was kicked from AP.

After reinstalling mdk3, everything works too, but now I alos have messages "Disconnecting xx:xx:xx:xx:xx:xx from xx:xx:xx:xx:xx:xx on channel" 11 #xx:xx:xx:xx:xx:xx are MACs of client and AP

@rad4day thank you for yours suggestion with cable, I did try it, but it does not make any difference.

My suggestion is to add option, that you can select ether mdk3 or aireplay deauth like at Handshake snopper.

Thank you all once again for yours help.

**Comment by MPX4132** [comment]
Awesome, sounds like you got it resolved. I'll close this issue bug if you have any more issues related to this, let us know here and we can reopen it.

**Comment by al3x32** [comment]
Hey @MPX4132 How did you upated your MDK3 with that gitgub ?
Step by step guide please :)

**Comment by MPX4132** [comment]
@al3x32 I think you might be asking the wrong person. I've never had issues updating mdk3 on Kali the regular way:
```
apt update && apt upgrade -y && apt autoremove -y && apt clean
```

If you want to upgrade your Kali distribution:
```
apt update && apt dist-upgrade -y && apt autoremove -y && apt clean
# Then you've got to reboot
```

**Comment by al3x32** [comment]
oh i got it. can you tell me how to do i update my MDK3 ? I downloaded that file from above github souce now dont know what to do next :( can you lead me step by step please ?

**Comment by MPX4132** [comment]
@al3x32 Sorry, I can't help you with that because I don't know about it. You can ask @spraragen88 since he's the one who posted the link.

**Comment by usama7628674** [comment]
@al3x32 mdk3 is archived,You should use mdk4.It supports both 2.4ghz and 5ghz.Take a look at here
https://github.com/aircrack-ng/mdk4

**Comment by al3x32** [comment]
can we use mdk4 on fluxion ? instead of mdk3? @usama7628674

**Comment by usama7628674** [comment]
@al3x32 Yes you can just close the mdk3 window which fluxion opens and fire up your own mdk4 window
manually provided you've adapter that supports 2.4ghz and 5ghz to deauthenticate clients from network.

**Comment by jitu3232** [comment]
It will good if someone  can add mdk4 support to fluxion.
Just a suggestion

**Comment by usama7628674** [comment]
@jitu3232 Yes,it is a good idea cuz mdk3 isn't maintained anymore.

**Comment by strasharo** [comment]
Is mdk4 shipped with Kali already? We can easily swap it, as long as it's part of the distribution, otherwise will start getting complaints about it not being available and folks not being able to install it.

**Comment by MPX4132** [comment]
@strasharo @usama7628674 @jitu3232 I've just checked and it looks like mdk4 does **not** come preinstall with Kali and it is **not** available on the repositories.

**Comment by usama7628674** [comment]
@MPX4132 Yeah you're right but I don't think it's a rocket science to install mdk4

**Comment by MPX4132** [comment]
@usama7628674 Have you seen some of the questions people ask sometimes? The issues some people open, with the most rudimentary questions. I'm not going to bother with mdk4 if people don't even bother reading the wiki.

**Comment by strasharo** [comment]
We would have to lock down the issues section if we switch to mdk4 prior it's being shipped with the distro. :D

**Comment by MPX4132** [comment]
Yeah, it'd be pretty bad.

**Comment by usama7628674** [comment]
@MPX4132 Yeah most people don't read wiki.mdk3 is working fine and it's just for deauthentication so don't bother with mdk4 until it'll be able to ship in distros.

**Comment by al3x32** [comment]
really ? is mdk3 working on fluxion ? because it creates fake ap but doesnt
deauth i guess because i dont get kicked from the router ?
how should i know weather it is working or not because it says perodically
re-reading every 3  second bla  bla :/

On Sun, May 6, 2018 at 4:48 AM, Usama Abdul Sattar <notifications@github.com

**Comment by strasharo** [comment]
From my personal experience it really depends on the driver and distribution. For example with Atheros on Kali it doesn't work for me either, works perfectly fine with the same hardware on Arch. So it's really up to the driver used and experience varies over distributions.

**Comment by al3x32** [comment]
ohhhh got it thanks

**Comment by al3x32** [comment]
@Usama how to connect mdk4 with fluxion?

**Comment by mishablokhin** [comment]
Hi. I set up mdk4 manually, target it on the victim AP BSSID and channel, but it kicks client devices from my Rogue AP too, not only from victim AP. What should I do in this case? I am using this command: 
`mdk4 fluxwl0 d -c 10 -B `10:7B:44:B4:1E:6C`
