### ISSUE TITLE
captive.gateway.lan loading indefinitely

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [FluxionNetwork/fluxion#551]
#### Summary
After connecting to the AP from my mobile, the browser connects to captive.gateway.lan and it doesn't open anything, it just keeps on loading and loading

##### What is the current behaviour?
It is not showing the enter password screen when connected to the AP

#### How to reproduce
Just open captive.gateway.lan on the browser in **kali linux arm** and it will load indefinitely.
![screenshot: ](https://user-images.githubusercontent.com/8942810/41817861-eaf49c02-77c0-11e8-987a-faa4a68b34fe.png)

##### What do you think the expected behaviour should be?
It should display the user to enter the wifi password when it loads captive.gateway.lan

#### FLUXION Info
FLUXION V4.12

#### BASH Info 
GNU bash, version 4.4.18(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan1) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
No Answer...

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.9.80-Re4son-v7+ (root@builder) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP Thu Apr 26 17:45:16 CDT 2018

**Comment by NavjotSinghMinhas** [comment]
Is there anyone monitoring for bugs?

**Comment by rad4day** [comment]
Sorry, we seem to be all very busy right now

**Comment by NavjotSinghMinhas** [comment]
Okay, thanks.

Will wait then :)
No problem.

**Comment by MPX4132** [comment]
@NavjotSinghMinhas Sorry for the wait, like @rad4day said, we've been busy. From what I recall, checking with the host machine will no longer work because of a change I made to keep things isolated. However, you can check using linux tools. Try the following when the `Captive Portal` attack is running:
```
# Check the DNS service
nslookup somebsdomain.lulz 192.168.254.1
# Should route you to 192.168.1.254.1, but any domain you input should route you to it.

# Check the Web service (by host address)
firefox http://192.168.254.1
# Or just navigate to that on a browser.
```

If those two work, the image you've shown shouldn't matter.

**Comment by NavjotSinghMinhas** [comment]
But i connected my mobile to this AP, captive.gateway.lan opens up and loads indefinitely on that device also.

**Comment by MPX4132** [comment]
@NavjotSinghMinhas Did you try what I mentioned, and did you get anything?

**Comment by MPX4132** [comment]
Also, there should be no problem with your driver. I use the exact same one for testing.

**Comment by NavjotSinghMinhas** [comment]
firefox reditects 192.168.254.1 to captive.gateway.lan and then server not found error.

**Comment by NavjotSinghMinhas** [comment]
firefox reditects 192.168.254.1 to captive.gateway.lan and then server not found error.

**Comment by MPX4132** [comment]
Make sure to use the protocol **http://** and don't assume it's there.

**Comment by MPX4132** [comment]
I'm closing this, since there was no response and I can't seem to be able to reproduce the issue. Once you respond we can reopen the issue if you can give us more information.

**Comment by nicolas4d** [comment]
Check the DNS service
nslookup somebsdomain.lulz 192.168.254.1
# Should route you to 192.168.1.254.1, but any domain you input should route you to it.
This is OK 

# Check the Web service (by host address)
firefox http://192.168.254.1
# Or just navigate to that on a browser
This is server not found. How can I fix?

**Comment by nicolas4d** [comment]
# Check the DNS service
nslookup somebsdomain.lulz 192.168.254.1
# Should route you to 192.168.1.254.1, but any domain you input should route you to it.

# Check the Web service (by host address)
firefox http://192.168.254.1
# Or just navigate to that on a browser.

@MPX4132 
I did check the DNS service. this route to 192.168.254.1
but when I check the web service. It's responed "Server Not Found". how can I fix this? Please!

**Comment by nicolas4d** [comment]
> @NavjotSinghMinhas Sorry for the wait, like @rad4day said, we've been busy. From what I recall, checking with the host machine will no longer work because of a change I made to keep things isolated. However, you can check using linux tools. Try the following when the `Captive Portal` attack is running:
> 
> ```
> # Check the DNS service
> nslookup somebsdomain.lulz 192.168.254.1
> # Should route you to 192.168.1.254.1, but any domain you input should route you to it.
> 
> # Check the Web service (by host address)
> firefox http://192.168.254.1
> # Or just navigate to that on a browser.
> ```
> If those two work, the image you've shown shouldn't matter.

I did check the DNS service. this route to 192.168.254.1
but when I check the web service. It's responed "Server Not Found". how can I fix this? Please!

**Comment by nicolas4d** [comment]
> @NavjotSinghMinhas Sorry for the wait, like @rad4day said, we've been busy. From what I recall, checking with the host machine will no longer work because of a change I made to keep things isolated. However, you can check using linux tools. Try the following when the `Captive Portal` attack is running:
> 
> ```
> # Check the DNS service
> nslookup somebsdomain.lulz 192.168.254.1
> # Should route you to 192.168.1.254.1, but any domain you input should route you to it.
> 
> # Check the Web service (by host address)
> firefox http://192.168.254.1
> # Or just navigate to that on a browser.
> ```
> If those two work, the image you've shown shouldn't matter.

hi @MPX4132 
I did check the DNS service. this route to 192.168.254.1
but when I check the web service. It's responed "Server Not Found". how can I fix this? Please!

**Comment by nicolas4d** [comment]
> > @NavjotSinghMinhas Sorry for the wait, like @rad4day said, we've been busy. From what I recall, checking with the host machine will no longer work because of a change I made to keep things isolated. However, you can check using linux tools. Try the following when the `Captive Portal` attack is running:
> > ```
> > # Check the DNS service
> > nslookup somebsdomain.lulz 192.168.254.1
> > # Should route you to 192.168.1.254.1, but any domain you input should route you to it.
> > 
> > # Check the Web service (by host address)
> > firefox http://192.168.254.1
> > # Or just navigate to that on a browser.
> > ```
> > If those two work, the image you've shown shouldn't matter.
> 
> hi @MPX4132
> I did check the DNS service. this route to 192.168.254.1
> but when I check the web service. It's responed "Server Not Found". how can I fix this? Please!

thanks @MPX4132 @rad4day @NavjotSinghMinhas first.
I fixed this problem. 
vim /etc/resolv.conf:
nameserver 192.168.254.1
put this first as first dns.

**Comment by NavjotSinghMinhas** [comment]
i tried both http://192.168.254.1 and captive.gateway.lam on both client and host, loads indefinitely.

As mentioned by @nicolas4d i tried adding nameserver 192.168.254.1 in /etc/resolv.conf
But still the same.

May be **open** the issue again and sorry for not responding earlier as i removed kali at that time.

**Comment by nicolas4d** [comment]
@NavjotSinghMinhas can you post the "/etc/resolv.conf" contents after you created the rogue ap with fluxion?

**Comment by NavjotSinghMinhas** [comment]
I selected no SSL, Disconnected emulation and TP-Link landing page (ID: 64 in options)

Also https calls were not routing to captive portal, may be i think it is because of no SSL selected.


![screenshot from 2019-03-01 14-50-48](https://user-images.githubusercontent.com/8942810/53645954-e878d900-3bee-11e9-9b11-bb5ab415e1c8.png)

**Comment by nicolas4d** [comment]
@NavjotSinghMinhas try SSL brother！ and tell me what happend! please

**Comment by NavjotSinghMinhas** [comment]
Hi @nicolas4d It works with SSL, BUT hold on....

1. All HTTPS calls resulted certificate error (I knew it would happen, that's why always selected no ssl)
2. HTTP requests works and routes to captive gateway. (BUT after opening 2-3 times, it wasn't loading OR was loading VERY VERY slow)

**Comment by nicolas4d** [comment]
> Hi @nicolas4d It works with SSL, BUT hold on....
> 
> 1. All HTTPS calls resulted certificate error (I knew it would happen, that's why always selected no ssl)
> 2. HTTP requests works and routes to captive gateway. (BUT after opening 2-3 times, it wasn't loading OR was loading VERY VERY slow)

@NavjotSinghMinhas hi! bro.
1. this is ok
2. It's fast in host Browser(like firefox or chrome) to me. but very very very slow with client(like Iphone or Android) that connect through rogou AP.

do you have any clue for this reason?
and help us @deltaxflux @MPX4132 . Please! Please! Please! Please!

**Comment by NavjotSinghMinhas** [comment]
yup, totally agree with you brother.

**Comment by nicolas4d** [comment]
they don't reopen  this Issue, why? @NavjotSinghMinhas bro!

**Comment by NavjotSinghMinhas** [comment]
may be busy, or are not getting notifications from a closed ticket.

You can create a new issue and redirect to this one, so they can reach here :)

**Comment by rad4day** [comment]
Sorry to leave you waiting.
We are in fact getting notifications. It's just that most of us are pretty busy. Also this project is for most of us not really our top priority project anymore. Therefore it's not that likely that we'll fix much stuff in the next few weeks / months.

Server not found sounds like either the webserver is not running at all or the firewall is misconfigured.

If any of you find the bug in the code, it would be nice submit a PR or give us a heads up.

**Comment by NavjotSinghMinhas** [comment]
Not a problem, but what could be the reason for slowness in client when host works fine.

I will look into code and learn it, but i am not familiar with Shell at all, i have worked with python, html and c though. So will not be a problem to learn it if you just give a little heads up about the problem. Thanks :)

**Comment by nicolas4d** [comment]
> Sorry to leave you waiting.
> We are in fact getting notifications. It's just that most of us are pretty busy. Also this project is for most of us not really our top priority project anymore. Therefore it's not that likely that we'll fix much stuff in the next few weeks / months.
> 
> Server not found sounds like either the webserver is not running at all or the firewall is misconfigured.
> 
> If any of you find the bug in the code, it would be nice submit a PR or give us a heads up.


I think this is not a code problem, but the envirenment or wifi card! I will buy another wifi card to test it. (laughing...) 

"firewall misiconfigured". 
I had barely thouched the firewall.
how to configure firewall? @rad4day

**Comment by nicolas4d** [comment]
I tested with rt3070. It's still slow. 
who can give me a clue?????? please!!!!!!

**Comment by nicolas4d** [comment]
> Sorry to leave you waiting.
> We are in fact getting notifications. It's just that most of us are pretty busy. Also this project is for most of us not really our top priority project anymore. Therefore it's not that likely that we'll fix much stuff in the next few weeks / months.
> 
> Server not found sounds like either the webserver is not running at all or the firewall is misconfigured.
> 
> If any of you find the bug in the code, it would be nice submit a PR or give us a heads up.

webserver in not running at all. @rad4day 
I checked lighttpd server status is inactive.
I try to manully start lighttpd, but always failed. how can I fix this? @rad4day

**Comment by Pride100** [comment]
Yeah!!!  You guys are right!!  Same problem here!!! Busy my ass 8 months ago!!! 
Soooo many problems with fluxion program and Developers!!!

Please gave me a link fluxion v4.10. Its more stable than v5 up.
Watch this so that u can see the problem.
 
https://youtu.be/48fr3BjMUCU

Also you guys make a video so that they can see how big is the issue is.

**Comment by Pride100** [comment]
Ive been trying to contact u guys on gmail and no resoponds!

**Comment by NavjotSinghMinhas** [comment]
@Pride100 looks like your DHCP is not working at all, but mine works though.

Request you to make a video from start to end i.e video where you run the "sudo ./fluxion.sh" to the hotspot connect.

Thanks

**Comment by Pride100** [comment]
Sure!!! Why not!!!
have a look
https://youtu.be/WEFLkQM8pGg
Ill be waiting 4 ur answer

On Mar 5, 2019 11:23 PM, "Navjot Singh Minhas" <notifications@github.com>
wrote:

@Pride100 <https://github.com/Pride100> looks like your DHCP is not working
at all, but mine works though.

Request you to make a video from start to end i.e video where you run the
"sudo ./fluxion.sh" to the hotspot connect.

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FluxionNetwork/fluxion/issues/551#issuecomment-469721060>,
or mute the thread

**Comment by NavjotSinghMinhas** [comment]
Ok, have you tried with Atheros instead of Realtek?

**Comment by Pride100** [comment]
I tried it so many many times and even worse it will stuck on last captive
portal, the one in chosing fake ap dns server and I choose one of any
English portal's then theres something 1 coding maybe starting captive
portal perhaps and it will stuck in there. No X-term tabs showing up. And
connot be cancelled.

On Mar 6, 2019 12:17 AM, "Navjot Singh Minhas" <notifications@github.com>
wrote:

Ok, have you tried with Atheros instead of Realtek?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FluxionNetwork/fluxion/issues/551#issuecomment-469742278>,
or mute the thread

**Comment by Pride100** [comment]
Thank you so Much! I thought my issue will finally be fixed/////Wow guys they pm at my gmail and I got blocked it they said any respawn will be lead as spam. Thank you for wasting my time. If this message can sent a picture then I will show you guys in print screen. That is called " WE ARE REALLY BUZY".
BUSY My ass!!!

**Comment by deltaxflux** [comment]
Yeah we are busy now but I have time after 22.3.

**Comment by NavjotSinghMinhas** [comment]
Hi @deltaxflux do you happen to have the original fluxion, the one that was published on github on other repo. I think it was version 2.x something.

**Comment by NavjotSinghMinhas** [comment]
Closed?

**Comment by muslimomar** [comment]
The same happens for me always, but restarting Fluxion like 2/3 times make it work.

**Comment by cjb900** [comment]
this was closed and fluxion has been updated many times since this was initially posted and closed. if you are having issues it would be better to open a new report and post your exact issue with the full details there or join the discord server for help https://discordapp.com/invite/G43gptk

**Comment by gladston** [comment]
Hello, I'm reading this post just today because @cjb900  has just informed that fluxion has been updated and probably the problem is gone.
   I recently had this problem with the **TL-WN722N V1** adapter. When the most recent version of fluxion was 6.5.
  After several formatting, downgrade and upgrade of Kali Linix, I solved the problem with these commands. **(Note: Atheros AR9271 is wlan1)**
Before running the fluxion script:
**airmon-ng check kill
airmon-ng start wlan1**

  With these two commands the problem solved for me, you will notice that before it appeared to select TL-WN722N as **wlan1** and now it is **wlan1mon**. I belive it's works well for you when it worked for me
  I leave this message here in the hope of helping you who are reading this in the future.

**Comment by dasReaver** [comment]
Hi! been having same problem and adding 192.168.254.1 to resolv.conf file finally helped, now every  android device connecting to the rogue ap will correctly display captive gateway. Without editing the conf file it only showed on PC-s
But now theres another problem. Rogue AP will be shown as (no internet) and android will ask if u really want to stay connected to that network.

What should be correct entries in resolc.conf file ? Mine works only if theres one nameserver ...254.1 and in this case no internet?
